# Generated by Django 3.2.6 on 2024-02-03 22:13

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('area', models.CharField(blank=True, max_length=500, null=True)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=500, null=True)),
                ('full_addres', models.CharField(blank=True, max_length=1000, null=True)),
                ('cheked_in_date', models.DateTimeField(blank=True, null=True)),
                ('cheked_out_date', models.DateTimeField(blank=True, null=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Premium', 'Premium')], max_length=100, null=True)),
                ('base_price', models.IntegerField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, choices=[('INR', 'INR'), ('US Dollar', 'US Dollar')], default='INR', max_length=50, null=True)),
                ('is_couple_allowd', models.BooleanField(blank=True, default=False, null=True)),
                ('can_locals_stay', models.BooleanField(blank=True, default=True, null=True)),
                ('should_coupon_applied', models.BooleanField(blank=True, default=False, null=True)),
                ('parent_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_rooms', to='mainapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('image_field', models.FileField(blank=True, null=True, upload_to=mainapp.models.room_images_upload_path)),
                ('parent_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_images', to='mainapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_price', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=3000, null=True)),
                ('is_coupon_applied', models.BooleanField(blank=True, default=False, null=True)),
                ('cheked_in_date', models.DateTimeField(blank=True, null=True)),
                ('cheked_out_date', models.DateTimeField(blank=True, null=True)),
                ('parent_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_details', to='mainapp.room')),
            ],
        ),
    ]
