# Generated by Django 3.2.6 on 2024-02-04 16:51

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_bookingdetail_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='front_img',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.room_front_images_upload_path),
        ),
    ]
