# Generated by Django 3.2.6 on 2024-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_room_front_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='front_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
