# Generated by Django 3.2.6 on 2024-02-04 17:18

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_room_front_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='front_img',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.room_front_images_upload_path),
        ),
    ]
