# Generated by Django 3.2.6 on 2024-02-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_room_front_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='customer_phn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
