# Generated by Django 3.2.6 on 2024-02-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20240211_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
