# Generated by Django 3.2.6 on 2024-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_bookingdetail_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_ac_availabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_housekeeping_availabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_parking_availabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_tv_availabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_wifi_availabel',
            field=models.BooleanField(default=True),
        ),
    ]
