# Generated by Django 3.2.6 on 2024-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20240309_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_ac_availabel',
            new_name='is_ac_available',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_housekeeping_availabel',
            new_name='is_housekeeping_available',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_parking_availabel',
            new_name='is_parking_available',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_tv_availabel',
            new_name='is_tv_available',
        ),
        migrations.AddField(
            model_name='room',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_room_approved_for_listing',
            field=models.BooleanField(default=False),
        ),
    ]
