# Generated by Django 3.2.6 on 2024-03-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_room_about_this_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_couple_allowd',
            new_name='is_couple_allowed',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_wifi_availabel',
            new_name='is_wifi_available',
        ),
    ]
