# Generated by Django 3.2.6 on 2024-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20240309_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='is_booking_approved',
            field=models.BooleanField(default=False),
        ),
    ]
