# Generated by Django 3.2.6 on 2024-03-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_bookingdetail_is_booking_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='distance_from_ap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance from nearest Air Port (km)'),
        ),
        migrations.AddField(
            model_name='room',
            name='distance_from_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance from nearest metro station (km)'),
        ),
        migrations.AddField(
            model_name='room',
            name='distance_from_rs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance from nearest railway station (km)'),
        ),
        migrations.AddField(
            model_name='room',
            name='nearest_airport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='nearest_metro_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='nearest_railway_station',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
