# Generated by Django 3.2.6 on 2024-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20240318_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contact_email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='contact_phn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='how_to_reach',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
