# Generated by Django 3.2.6 on 2024-02-08 19:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_img',
            field=models.FileField(blank=True, null=True, upload_to=user.models.user_dp_path),
        ),
    ]
